DROP SCHEMA IF EXISTS loads CASCADE;
DROP SCHEMA IF EXISTS core CASCADE;
DROP SCHEMA IF EXISTS geography CASCADE;
DROP SCHEMA IF EXISTS catalog CASCADE;
DROP SCHEMA IF EXISTS agroforestry CASCADE;

CREATE SCHEMA IF NOT EXISTS loads;
CREATE SCHEMA IF NOT EXISTS core;
CREATE SCHEMA IF NOT EXISTS geography;
CREATE SCHEMA IF NOT EXISTS catalog;
CREATE SCHEMA IF NOT EXISTS agroforestry;

DELETE FROM django_migrations WHERE app IN ('catalog', 'core', 'geography', 'catalog', 'agroforestry');
