server {
  listen 80;
  location / {
    proxy_pass "$django_url:$django_port";
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";
    add_header Referrer-Policy "no-referrer";
    add_header Content-Security-Policy "default-src 'self'" always;
    add_header Allow "GET, HEAD, POST, DELETE" always;
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains" always;
    proxy_set_header X-Original-URL "";
    proxy_set_header X-Rewrite-URL "";
    proxy_set_header X-Forwarded-Server "";
    proxy_set_header X-Forwarded-Host "";
    proxy_set_header X-Host "";
  }
}
