# Generated by Django 5.2.6 on 2025-10-22 15:27

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema', models.JSONField()),
                ('is_nullable', models.BooleanField(db_default=True)),
                ('position', models.IntegerField()),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"core"."source_fields"',
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pt_br', models.CharField(unique=True)),
                ('en', models.CharField(blank=True, null=True, unique=True)),
                ('es', models.CharField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': '"core"."texts"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField()),
                ('last_name', models.CharField()),
                ('email', models.CharField(unique=True)),
                ('password', models.CharField()),
                ('role', models.CharField(blank=True, db_default='regular', null=True)),
                ('occupation', models.CharField()),
                ('company', models.CharField(blank=True, null=True)),
                ('country', models.CharField(blank=True, null=True)),
                ('state', models.CharField(blank=True, null=True)),
                ('municipality', models.CharField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField(blank=True, null=True)),
                ('is_staff', models.BooleanField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('is_verified', models.BooleanField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': '"core"."users"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, null=True, unique=True)),
                ('creator_notes', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"core"."sources"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField()),
                ('status', models.CharField(choices=[('proposed', 'Pro'), ('accepted', 'Acc'), ('rejected', 'Rej')], db_default='proposed')),
                ('proposer_comment', models.CharField(blank=True, max_length=300, null=True)),
                ('rejector_comment', models.CharField(blank=True, max_length=300, null=True)),
                ('endorsements_count', models.IntegerField(db_default=0)),
                ('proposed_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('acceptor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='accepted_contents', to=settings.AUTH_USER_MODEL)),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='proposed_contents', to=settings.AUTH_USER_MODEL)),
                ('rejector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rejected_contents', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contents', to='core.source')),
            ],
            options={
                'db_table': '"core"."contents"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SourceFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField()),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.sourcefield')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='field_values', to='core.source')),
            ],
            options={
                'db_table': '"core"."source_field_values"',
            },
        ),
        migrations.CreateModel(
            name='SourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, 'type'), (2, 'subtype')])),
                ('is_static', models.BooleanField()),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='core.sourcetype')),
                ('name_text', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='core.text')),
            ],
            options={
                'db_table': '"core"."source_types"',
            },
        ),
        migrations.AddField(
            model_name='sourcefield',
            name='source_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='field_set', to='core.sourcetype'),
        ),
        migrations.AddField(
            model_name='source',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.sourcetype'),
        ),
        migrations.AddField(
            model_name='sourcefield',
            name='description_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='description_text_fields', to='core.text'),
        ),
        migrations.AddField(
            model_name='sourcefield',
            name='name_text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='name_text_fields', to='core.text'),
        ),
        migrations.CreateModel(
            name='ContentEndorsement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='endorsements', to='core.content')),
                ('endorser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"core"."content_endorsements"',
                'managed': True,
                'unique_together': {('content', 'endorser', 'deleted_at')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='sourcefield',
            unique_together={('source_type', 'name_text')},
        ),
    ]
