# Generated by Django 5.2.6 on 2025-09-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcefield',
            name='position',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sourcefield',
            name='is_nullable',
            field=models.BooleanField(db_default=True),
        ),
    ]
