# Generated by Django 5.2.6 on 2026-08-29 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='content',
            table='contents',
        ),
        migrations.AlterModelTable(
            name='contentendorsement',
            table='content_endorsements',
        ),
        migrations.AlterModelTable(
            name='source',
            table='sources',
        ),
        migrations.AlterModelTable(
            name='sourcefield',
            table='source_fields',
        ),
        migrations.AlterModelTable(
            name='sourcefieldvalue',
            table='source_field_values',
        ),
        migrations.AlterModelTable(
            name='sourcetype',
            table='source_types',
        ),
        migrations.AlterModelTable(
            name='text',
            table='texts',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
