# Generated by Django 5.2.6 on 2025-09-08 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sourcefield_position_alter_sourcefield_is_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourcefield',
            name='data_type',
        ),
    ]
