# Generated by Django 5.2.6 on 2025-09-08 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_sourcefield_data_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sourcefield',
            old_name='data_schema',
            new_name='schema',
        ),
    ]
