# Generated by Django 5.2.6 on 2025-09-13 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_data_schema_sourcefield_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='status',
            field=models.CharField(choices=[('proposed', 'Pro'), ('accepted', 'Acc'), ('rejected', 'Rej')], db_default='proposed'),
        ),
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(),
        ),
    ]
