# Generated by Django 5.2.6 on 2025-09-24 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_content_status_alter_content_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='endorsements',
            new_name='endorsements_count',
        ),
        migrations.AlterField(
            model_name='contentendorsement',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='endorsements', to='core.content'),
        ),
    ]
