# Generated by Django 5.2.6 on 2025-09-08 05:43

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('name_text', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='core.text')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.source')),
            ],
            options={
                'db_table': '"geography"."countries"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Biome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('area', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.source')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geography.country')),
            ],
            options={
                'db_table': '"geography"."biomes"',
                'managed': True,
                'unique_together': {('name', 'country')},
            },
        ),
        migrations.CreateModel(
            name='SoilAcidityLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph_min', models.DecimalField(decimal_places=1, max_digits=3)),
                ('ph_max', models.DecimalField(decimal_places=1, max_digits=3)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('name_text', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.text')),
            ],
            options={
                'db_table': '"geography"."soil_acidity_levels"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('code', models.CharField(blank=True, null=True)),
                ('area', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geography.country')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.source')),
            ],
            options={
                'db_table': '"geography"."states"',
                'managed': True,
                'unique_together': {('name', 'country')},
            },
        ),
        migrations.CreateModel(
            name='SoilTextureArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('texture', models.CharField()),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geography.country')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.source')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='geography.state')),
            ],
            options={
                'db_table': '"geography"."soil_texture_areas"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SoilPhMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rast', django.contrib.gis.db.models.fields.RasterField(srid=4326)),
                ('filename', models.CharField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geography.country')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.source')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='geography.state')),
            ],
            options={
                'db_table': '"geography"."soil_ph_maps"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('area', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('fiscal_module_size_sqrm', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.source')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geography.state')),
            ],
            options={
                'db_table': '"geography"."municipalities"',
                'managed': True,
                'unique_together': {('name', 'state')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyDroughtArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('year', models.CharField()),
                ('month', models.CharField()),
                ('drought_level', models.CharField()),
                ('drought_level_code', models.CharField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geography.country')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.source')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='geography.state')),
            ],
            options={
                'db_table': '"geography"."monthly_drought_areas"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ClimateNormal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_first_year', models.IntegerField(blank=True, null=True)),
                ('period_last_year', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('precipitation_mm', models.IntegerField(blank=True, null=True)),
                ('temperature_c_average', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.source')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geography.country')),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='geography.municipality')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='geography.state')),
            ],
            options={
                'db_table': '"geography"."climate_normals"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VegetationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geography.country')),
            ],
            options={
                'db_table': '"geography"."vegetation_types"',
                'managed': True,
                'unique_together': {('name', 'country')},
            },
        ),
        migrations.CreateModel(
            name='VegetationArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('biome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='geography.biome')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geography.country')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.source')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='geography.state')),
                ('vegetation_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geography.vegetationtype')),
            ],
            options={
                'db_table': '"geography"."vegetation_areas"',
                'managed': True,
            },
        ),
    ]
