# Simulador Agroflorestal Regenera (SAR)
# Copyright (C) 2026  Lucas Marques and Regenera Mata Atlântica

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses>.

# Generated by Django 5.2.6 on 2026-02-04 22:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlydroughtarea',
            name='drought_level',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='monthlydroughtarea',
            name='drought_level_code',
            field=models.CharField(blank=True, choices=[('Si', 'ausente'), ('S0', 'fraca'), ('S1', 'moderada'), ('S2', 'grave'), ('S3', 'extrema'), ('S4', 'excepcional')], null=True),
        ),
    ]
