# Generated by Django 5.2.6 on 2026-02-04 22:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlydroughtarea',
            name='drought_level',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='monthlydroughtarea',
            name='drought_level_code',
            field=models.CharField(blank=True, choices=[('Si', 'ausente'), ('S0', 'fraca'), ('S1', 'moderada'), ('S2', 'grave'), ('S3', 'extrema'), ('S4', 'excepcional')], null=True),
        ),
    ]
