# Generated by Django 5.2.6 on 2025-09-25 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetationarea',
            name='biome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vegetation_areas', to='geography.biome'),
        ),
        migrations.AlterField(
            model_name='vegetationarea',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vegetation_areas', to='geography.country'),
        ),
        migrations.AlterField(
            model_name='vegetationarea',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vegetation_areas', to='geography.state'),
        ),
        migrations.AlterField(
            model_name='vegetationarea',
            name='vegetation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vegetation_areas', to='geography.vegetationtype'),
        ),
    ]
