# Generated by Django 5.2.6 on 2026-08-29 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0002_alter_monthlydroughtarea_drought_level_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='biome',
            table='biomes',
        ),
        migrations.AlterModelTable(
            name='climatenormal',
            table='climate_normals',
        ),
        migrations.AlterModelTable(
            name='country',
            table='countries',
        ),
        migrations.AlterModelTable(
            name='monthlydroughtarea',
            table='monthly_drought_areas',
        ),
        migrations.AlterModelTable(
            name='municipality',
            table='municipalities',
        ),
        migrations.AlterModelTable(
            name='soilaciditylevel',
            table='soil_acidity_levels',
        ),
        migrations.AlterModelTable(
            name='soilphmap',
            table='soil_ph_maps',
        ),
        migrations.AlterModelTable(
            name='soiltexturearea',
            table='soil_texture_areas',
        ),
        migrations.AlterModelTable(
            name='soiltexturetype',
            table='soil_texture_types',
        ),
        migrations.AlterModelTable(
            name='state',
            table='states',
        ),
        migrations.AlterModelTable(
            name='vegetationarea',
            table='vegetation_areas',
        ),
        migrations.AlterModelTable(
            name='vegetationtype',
            table='vegetation_types',
        ),
    ]
