# Generated by Django 5.2.6 on 2025-12-17 00:26

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0001_initial'),
        ('geography', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
                ('arguments_schema', models.JSONField(blank=True, null=True)),
                ('body', models.JSONField()),
                ('return_schema', models.JSONField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"agroforestry"."functions"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CroppingPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('copied_pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='agroforestry.croppingpattern')),
                ('public_content', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.content')),
            ],
            options={
                'db_table': '"agroforestry"."cropping_patterns"',
                'managed': True,
                'unique_together': {('name', 'author')},
            },
        ),
        migrations.CreateModel(
            name='CroppingPatternRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('distance_to_next_position_cm', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('copied_row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='agroforestry.croppingpatternrow')),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agroforestry.croppingpattern')),
                ('purpose_text', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.text')),
            ],
            options={
                'db_table': '"agroforestry"."cropping_pattern_rows"',
                'managed': True,
                'unique_together': {('pattern', 'position')},
            },
        ),
        migrations.CreateModel(
            name='CroppingPatternCrop',
            fields=[
                ('pk', models.CompositePrimaryKey('pattern_id', 'pattern_row_id', 'position', blank=True, editable=False, primary_key=True, serialize=False)),
                ('position', models.IntegerField()),
                ('distance_to_next_position_cm', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agroforestry.croppingpattern')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.plant')),
                ('pattern_row', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agroforestry.croppingpatternrow')),
            ],
            options={
                'db_table': '"agroforestry"."cropping_pattern_crops"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CroppingRowPurposeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('option_text', models.OneToOneField(db_comment='[diversidade, preenchimento, anuais, cobertura, outra]', on_delete=django.db.models.deletion.DO_NOTHING, to='core.text')),
            ],
            options={
                'db_table': '"agroforestry"."cropping_row_purpose_options"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('description', models.TextField(blank=True, null=True)),
                ('logical_operator', models.CharField(blank=True, null=True)),
                ('is_parent', models.BooleanField(blank=True, null=True)),
                ('public', models.BooleanField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('copied_rule_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='copy_rule_sets', to='agroforestry.ruleset')),
                ('parent_rule_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children_rule_sets', to='agroforestry.ruleset')),
            ],
            options={
                'db_table': '"agroforestry"."rule_sets"',
                'managed': True,
                'unique_together': {('name', 'author')},
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField()),
                ('metric_function_input', models.JSONField()),
                ('metric_post_transforms', models.JSONField(blank=True, null=True)),
                ('comparison_operator', models.CharField()),
                ('threshold_constant', models.DecimalField(decimal_places=5, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('metric_function', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agroforestry.function')),
                ('rule_set', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agroforestry.ruleset')),
            ],
            options={
                'db_table': '"agroforestry"."rules"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('farm', 'Frm'), ('field', 'Fld')])),
                ('center', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('perimeter', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('biome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='geography.biome')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geography.country')),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='geography.municipality')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='geography.state')),
                ('vegetation_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='geography.vegetationtype')),
            ],
            options={
                'db_table': '"agroforestry"."site"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='agroforestry.site')),
            ],
            options={
                'db_table': '"agroforestry"."farms"',
                'managed': True,
                'unique_together': {('name', 'user')},
            },
        ),
        migrations.CreateModel(
            name='SiteTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('section', models.CharField()),
                ('schema', models.JSONField()),
                ('is_nullable', models.BooleanField()),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name_text', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='name_text_site_traits', to='core.text')),
                ('section_text', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='section_text_site_traits', to='core.text')),
            ],
            options={
                'db_table': '"agroforestry"."site_traits"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlantSiteFitting',
            fields=[
                ('pk', models.CompositePrimaryKey('plant_trait', 'site_trait', blank=True, editable=False, primary_key=True, serialize=False)),
                ('pre_transforms', models.JSONField(blank=True, null=True)),
                ('fitting_function_input', models.JSONField()),
                ('fitting_weight', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('fitting_function', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agroforestry.function')),
                ('plant_trait', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.trait')),
                ('site_trait', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agroforestry.sitetrait')),
            ],
            options={
                'db_table': '"agroforestry"."plant_site_fitting"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SiteTraitTextValueOption',
            fields=[
                ('pk', models.CompositePrimaryKey('trait', 'option_text', blank=True, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('option_text', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.text')),
                ('trait', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agroforestry.sitetrait')),
            ],
            options={
                'db_table': '"agroforestry"."site_trait_text_value_options"',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='sitetrait',
            name='text_value_options',
            field=models.ManyToManyField(through='agroforestry.SiteTraitTextValueOption', to='core.text'),
        ),
        migrations.CreateModel(
            name='SiteTraitValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='agroforestry.site')),
                ('trait', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agroforestry.sitetrait')),
            ],
            options={
                'db_table': '"agroforestry"."site_trait_values"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SiteTraitValueText',
            fields=[
                ('pk', models.CompositePrimaryKey('site_trait_value', 'text', blank=True, editable=False, primary_key=True, serialize=False)),
                ('site_trait_value', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agroforestry.sitetraitvalue')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.text')),
            ],
            options={
                'db_table': '"agroforestry"."site_trait_value_texts"',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='sitetraitvalue',
            name='texts',
            field=models.ManyToManyField(through='agroforestry.SiteTraitValueText', to='core.text'),
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('cropping_summary', models.JSONField(blank=True, null=True)),
                ('cropping_geometry', models.JSONField(blank=True, null=True)),
                ('cropping_pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='agroforestry.croppingpattern')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agroforestry.farm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('cropping_rule_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='agroforestry.ruleset')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='agroforestry.site')),
            ],
            options={
                'db_table': '"agroforestry"."fields"',
                'managed': True,
                'unique_together': {('name', 'farm', 'user')},
            },
        ),
    ]
