# Simulador Agroflorestal Regenera (SAR)
# Copyright (C) 2026  Lucas Marques and Regenera Mata Atlântica

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses>.

# Generated by Django 5.2.6 on 2026-01-05 15:49

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agroforestry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='polygon',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
