# Generated by Django 5.2.6 on 2025-12-23 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agroforestry', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='perimeter',
            new_name='polygon',
        ),
    ]
