# Generated by Django 5.2.6 on 2026-01-05 15:49

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agroforestry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='polygon',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
