# Generated by Django 5.2.6 on 2026-01-08 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroforestry', '0002_alter_site_polygon'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitetrait',
            name='position',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
