# Generated by Django 5.2.6 on 2025-12-23 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agroforestry', '0002_rename_perimeter_site_polygon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='center',
            new_name='location',
        ),
    ]
