# Generated by Django 5.2.6 on 2026-01-14 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroforestry', '0003_sitetrait_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitetraitvalue',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trait_values', to='agroforestry.site'),
        ),
    ]
