# Generated by Django 5.2.6 on 2025-12-23 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agroforestry', '0003_rename_center_site_location'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='site',
            table='"agroforestry"."sites"',
        ),
    ]
