# Generated by Django 5.2.6 on 2026-01-22 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agroforestry', '0004_alter_sitetraitvalue_site'),
    ]

    operations = [
        migrations.RenameField(
            model_name='function',
            old_name='arguments_schema',
            new_name='input_schema',
        ),
    ]
