# Simulador Agroflorestal Regenera (SAR)
# Copyright (C) 2026  Lucas Marques and Regenera Mata Atlântica

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses>.

# Generated by Django 5.2.6 on 2026-01-22 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroforestry', '0005_rename_arguments_schema_function_input_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='body',
            field=models.TextField(),
        ),
    ]
