# Generated by Django 5.2.6 on 2026-01-22 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroforestry', '0005_rename_arguments_schema_function_input_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='body',
            field=models.TextField(),
        ),
    ]
