# Generated by Django 5.2.6 on 2025-12-24 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroforestry', '0005_alter_croppingpattern_created_at_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitetraittextvalueoption',
            name='option_text',
        ),
        migrations.AddField(
            model_name='sitetrait',
            name='description_text',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='description_text_site_traits', to='core.text'),
        ),
        migrations.AddField(
            model_name='sitetraittextvalueoption',
            name='description_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='description_text_site_options', to='core.text'),
        ),
        migrations.AddField(
            model_name='sitetraittextvalueoption',
            name='value_text',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='value_text_site_options', to='core.text'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sitetrait',
            name='text_value_options',
            field=models.ManyToManyField(through='agroforestry.SiteTraitTextValueOption', through_fields=('trait', 'value_text'), to='core.text'),
        ),
        migrations.AlterField(
            model_name='sitetraittextvalueoption',
            name='pk',
            field=models.CompositePrimaryKey('trait', 'value_text', blank=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
