# Generated by Django 5.2.6 on 2026-04-30 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroforestry', '0006_alter_function_body'),
        ('catalog', '0003_alter_traitvalue_trait'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='croppingpatterncrop',
            name='distance_to_next_position_cm',
        ),
        migrations.RemoveField(
            model_name='croppingpatternrow',
            name='distance_to_next_position_cm',
        ),
        migrations.AddField(
            model_name='croppingpatterncrop',
            name='distance_to_next_crop_m',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='croppingpatternrow',
            name='distance_to_next_row_m',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='field',
            name='crops_offset_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='rows_angle_deg',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='rows_offset_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='croppingpatterncrop',
            name='position',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='croppingpatternrow',
            name='position',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='plantsitefitting',
            name='plant_trait',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='site_fitting', to='catalog.trait'),
        ),
        migrations.AlterField(
            model_name='plantsitefitting',
            name='site_trait',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='plant_fitting', to='agroforestry.sitetrait'),
        ),
        migrations.AlterField(
            model_name='sitetraitvalue',
            name='trait',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='values', to='agroforestry.sitetrait'),
        ),
        migrations.DeleteModel(
            name='CroppingRowPurposeOption',
        ),
    ]
