# Generated by Django 5.2.6 on 2026-04-30 23:08

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroforestry', '0007_remove_croppingpatterncrop_distance_to_next_position_cm_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='croppingpatternrow',
            name='purpose_text',
        ),
        migrations.CreateModel(
            name='CroppingRowPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('text', models.OneToOneField(db_comment='[diversidade, preenchimento, anuais, cobertura, outra]', on_delete=django.db.models.deletion.DO_NOTHING, to='core.text')),
            ],
            options={
                'db_table': '"agroforestry"."cropping_row_purpose"',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='croppingpatternrow',
            name='purpose',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='agroforestry.croppingrowpurpose'),
            preserve_default=False,
        ),
    ]
