# Generated by Django 5.2.6 on 2026-05-22 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroforestry', '0008_remove_croppingpatternrow_purpose_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='croppingpattern',
            old_name='copied_pattern',
            new_name='source_pattern',
        ),
        migrations.RemoveField(
            model_name='croppingpatternrow',
            name='copied_row',
        ),
        migrations.AddField(
            model_name='croppingpattern',
            name='rows_hash',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='croppingpattern',
            name='is_public',
            field=models.BooleanField(db_default=True),
        ),
        migrations.AlterField(
            model_name='croppingpatterncrop',
            name='pattern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pattern_crops', to='agroforestry.croppingpattern'),
        ),
        migrations.AlterField(
            model_name='croppingpatterncrop',
            name='pattern_row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='row_crops', to='agroforestry.croppingpatternrow'),
        ),
        migrations.AlterField(
            model_name='croppingpatterncrop',
            name='pk',
            field=models.CompositePrimaryKey('pattern_row_id', 'position', blank=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='croppingpatternrow',
            name='pattern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pattern_rows', to='agroforestry.croppingpattern'),
        ),
        migrations.AlterField(
            model_name='croppingpatternrow',
            name='purpose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='agroforestry.croppingrowpurpose'),
        ),
        migrations.AlterField(
            model_name='field',
            name='cropping_pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pattern_fields', to='agroforestry.croppingpattern'),
        ),
    ]
