# Generated by Django 5.2.6 on 2026-06-12 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroforestry', '0009_rename_copied_pattern_croppingpattern_source_pattern_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='cropping_geometry',
        ),
        migrations.RemoveField(
            model_name='field',
            name='cropping_pattern',
        ),
        migrations.RemoveField(
            model_name='field',
            name='cropping_rule_set',
        ),
        migrations.RemoveField(
            model_name='field',
            name='cropping_summary',
        ),
        migrations.RemoveField(
            model_name='field',
            name='crops_offset_m',
        ),
        migrations.RemoveField(
            model_name='field',
            name='rows_angle_deg',
        ),
        migrations.RemoveField(
            model_name='field',
            name='rows_offset_m',
        ),
        migrations.AddField(
            model_name='croppingpatternrow',
            name='crops_offset_m',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='field',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fields', to='agroforestry.farm'),
        ),
        migrations.CreateModel(
            name='Cropping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rows_angle_deg', models.SmallIntegerField()),
                ('rows_offset_m', models.DecimalField(decimal_places=2, max_digits=6)),
                ('crops_offset_m', models.DecimalField(decimal_places=2, max_digits=6)),
                ('summary', models.JSONField(blank=True, null=True)),
                ('geometry', models.JSONField(blank=True, null=True)),
                ('pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pattern_fields', to='agroforestry.croppingpattern')),
                ('rule_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='agroforestry.ruleset')),
            ],
            options={
                'db_table': '"agroforestry"."croppings"',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='field',
            name='cropping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='agroforestry.cropping'),
        ),
    ]
