# Generated by Django 5.2.6 on 2026-07-10 23:27

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agroforestry', '0010_remove_field_cropping_geometry_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='croppingpatterncrop',
            options={'managed': True, 'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='croppingpatternrow',
            options={'managed': True, 'ordering': ['position']},
        ),
        migrations.AlterField(
            model_name='site',
            name='polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
