# Generated by Django 5.2.6 on 2026-08-29 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroforestry', '0011_alter_croppingpatterncrop_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropping',
            name='pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pattern_croppings', to='agroforestry.croppingpattern'),
        ),
        migrations.AlterModelTable(
            name='cropping',
            table='croppings',
        ),
        migrations.AlterModelTable(
            name='croppingpattern',
            table='cropping_patterns',
        ),
        migrations.AlterModelTable(
            name='croppingpatterncrop',
            table='cropping_pattern_crops',
        ),
        migrations.AlterModelTable(
            name='croppingpatternrow',
            table='cropping_pattern_rows',
        ),
        migrations.AlterModelTable(
            name='croppingrowpurpose',
            table='cropping_row_purposes',
        ),
        migrations.AlterModelTable(
            name='farm',
            table='farms',
        ),
        migrations.AlterModelTable(
            name='field',
            table='fields',
        ),
        migrations.AlterModelTable(
            name='function',
            table='functions',
        ),
        migrations.AlterModelTable(
            name='plantsitefitting',
            table='plant_site_fitting',
        ),
        migrations.AlterModelTable(
            name='rule',
            table='rules',
        ),
        migrations.AlterModelTable(
            name='ruleset',
            table='rule_sets',
        ),
        migrations.AlterModelTable(
            name='site',
            table='sites',
        ),
        migrations.AlterModelTable(
            name='sitetrait',
            table='site_traits',
        ),
        migrations.AlterModelTable(
            name='sitetraittextvalueoption',
            table='site_trait_text_value_options',
        ),
        migrations.AlterModelTable(
            name='sitetraitvalue',
            table='site_trait_values',
        ),
        migrations.AlterModelTable(
            name='sitetraitvaluetext',
            table='site_trait_value_texts',
        ),
    ]
