# Generated by Django 5.2.6 on 2026-08-29 00:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agroforestry', '0012_alter_cropping_pattern_alter_cropping_table_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='croppingpattern',
            unique_together={('name', 'author', 'deleted_at')},
        ),
    ]
