# Generated by Django 5.2.6 on 2026-09-01 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroforestry', '0013_alter_croppingpattern_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropping',
            name='pattern',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pattern_croppings', to='agroforestry.croppingpattern'),
            preserve_default=False,
        ),
    ]
