# Generated by Django 5.2.6 on 2025-10-22 15:27

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_taxon_name', models.CharField(blank=True, null=True, unique=True)),
                ('accepted_family_name', models.CharField(blank=True, null=True)),
                ('color_hex', models.CharField(blank=True, null=True, unique=True)),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='core.content')),
            ],
            options={
                'db_table': '"catalog"."plants"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NaturalOccurrenceRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='geography.biome')),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='core.content')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geography.country')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='geography.state')),
                ('vegetation_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='geography.vegetationtype')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='natural_occurrence_regions', to='catalog.plant')),
            ],
            options={
                'db_table': '"catalog"."natural_occurrence_regions"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InvasionRiskRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxon_name', models.CharField()),
                ('eicat_category', models.CharField(blank=True, choices=[('Moderate', 'moderate'), ('Major', 'major'), ('Massive', 'massive')], null=True)),
                ('biome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='geography.biome')),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='core.content')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geography.country')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='geography.state')),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='invasion_risk_regions', to='catalog.plant')),
            ],
            options={
                'db_table': '"catalog"."invasion_risk_regions"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PopularName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='core.content')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='popular_names', to='catalog.plant')),
            ],
            options={
                'db_table': '"catalog"."popular_names"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Taxon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField()),
                ('genus', models.CharField()),
                ('species', models.CharField()),
                ('subspecies', models.CharField(blank=True, null=True)),
                ('variety', models.CharField(blank=True, null=True)),
                ('taxonomic_status', models.CharField(choices=[('accepted', 'Acc'), ('synonym', 'Syn')])),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='core.content')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='taxa', to='catalog.plant')),
            ],
            options={
                'db_table': '"catalog"."taxa"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('section', models.CharField(blank=True, null=True)),
                ('data_type', models.CharField()),
                ('schema', models.JSONField()),
                ('is_nullable', models.BooleanField()),
                ('is_site_specific', models.BooleanField()),
                ('numeric_value_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('numeric_value_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name_text', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='name_text_traits', to='core.text')),
                ('section_text', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='section_text_traits', to='core.text')),
            ],
            options={
                'db_table': '"catalog"."traits"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TraitTextValueOption',
            fields=[
                ('pk', models.CompositePrimaryKey('trait', 'option_text', blank=True, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('option_text', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.text')),
                ('trait', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.trait')),
            ],
            options={
                'db_table': '"catalog"."trait_text_value_options"',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='trait',
            name='text_value_options',
            field=models.ManyToManyField(through='catalog.TraitTextValueOption', to='core.text'),
        ),
        migrations.CreateModel(
            name='TraitValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField()),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trait_value', to='core.content')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trait_values', to='catalog.plant')),
                ('trait', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.trait')),
            ],
            options={
                'db_table': '"catalog"."trait_values"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TraitValueText',
            fields=[
                ('pk', models.CompositePrimaryKey('trait_value', 'text', blank=True, editable=False, primary_key=True, serialize=False)),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.text')),
                ('trait_value', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.traitvalue')),
            ],
            options={
                'db_table': '"catalog"."trait_values_texts"',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='traitvalue',
            name='texts',
            field=models.ManyToManyField(through='catalog.TraitValueText', to='core.text'),
        ),
        migrations.AlterUniqueTogether(
            name='trait',
            unique_together={('name_text', 'section_text')},
        ),
    ]
