# Generated by Django 5.2.6 on 2025-09-09 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trait',
            old_name='data_schema',
            new_name='schema',
        ),
    ]
