# Generated by Django 5.2.6 on 2026-01-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='accepted_taxon_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='color_hex',
            field=models.CharField(blank=True, null=True),
        ),
    ]
