# Generated by Django 5.2.6 on 2026-04-30 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_plant_accepted_taxon_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traitvalue',
            name='trait',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='values', to='catalog.trait'),
        ),
    ]
