# Generated by Django 5.2.6 on 2025-09-13 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_data_schema_trait_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxon',
            name='taxonomic_status',
            field=models.CharField(choices=[('accepted', 'Acc'), ('synonym', 'Syn')]),
        ),
    ]
