# Generated by Django 5.2.6 on 2025-09-30 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_taxon_taxonomic_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='accepted_family_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='accepted_taxon_name',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='color_hex',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
