# Generated by Django 5.2.6 on 2026-07-17 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_traitvalue_trait'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='main_popular_name',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plant',
            name='accepted_family_name',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plant',
            name='accepted_taxon_name',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plant',
            name='color_hex',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
