# Generated by Django 5.2.6 on 2026-08-29 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_plant_main_popular_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='invasionriskregion',
            table='invasion_risk_regions',
        ),
        migrations.AlterModelTable(
            name='naturaloccurrenceregion',
            table='natural_occurrence_regions',
        ),
        migrations.AlterModelTable(
            name='plant',
            table='plants',
        ),
        migrations.AlterModelTable(
            name='popularname',
            table='popular_names',
        ),
        migrations.AlterModelTable(
            name='taxon',
            table='taxa',
        ),
        migrations.AlterModelTable(
            name='trait',
            table='traits',
        ),
        migrations.AlterModelTable(
            name='traittextvalueoption',
            table='trait_text_value_options',
        ),
        migrations.AlterModelTable(
            name='traitvalue',
            table='trait_values',
        ),
        migrations.AlterModelTable(
            name='traitvaluetext',
            table='trait_values_texts',
        ),
    ]
